### PR TITLE
Add support for String.prototype.matchAll()

### PR DESCRIPTION
**Pull request by kylemclean**
This PR adds support for `String.prototype.matchAll(regexp)` where `regexp` is an RE2 instance.

BEGIN_COMMIT_OVERRIDE
feat: Add support for String.prototype.matchAll()
END_COMMIT_OVERRIDE

### CODE REVIEW

**Comment by murgatroid99** [comment]
Is the new `test_matchAll.js` actually sourced from https://github.com/uhop/node-re2? If not, it doesn't belong in `third_party/node-re2`, and should instead be placed in a new `tests` folder in the root directory.

**Comment by kylemclean** [comment]
> Is the new `test_matchAll.js` actually sourced from https://github.com/uhop/node-re2? If not, it doesn't belong in `third_party/node-re2`, and should instead be placed in a new `tests` folder in the root directory.

Yes, it is from that repository.

**Review by murgatroid99 — APPROVED** [review]
Thank you for your contribution.

**Comment by murgatroid99** [comment]
This has been released in version 1.1.0

**Pull request merged**
